name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: Content

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore
        run: dotnet restore Vesia.Template.slnx

      - name: Setup Mono
        run: sudo apt-get update && sudo apt-get install -y mono-devel
        working-directory: .

      - name: Setup NuGet CLI
        uses: NuGet/setup-nuget@v2

      - name: Pack
        working-directory: .
        run: nuget pack Vesia.Foundation.nuspec -NoDefaultExcludes -OutputDirectory ./nupkg -Properties Configuration=Release

      - name: NuGet Login (OIDC)
        id: login
        uses: NuGet/login@v1
        with:
          user: ${{ vars.NUGET_USER }}

      - name: Push to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        working-directory: .